version: 2
sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: shilpa-cis9440
    schema: nyc_homework_raw_data
    tables:
      - name: source_service_requests_homework
        description: |
          NYC 311 service requests for Dept of Transportation.
          One row per service request.